drop table if exists users cascade;
create table users (
   id bigint generated by default as identity,
   email varchar(255) unique,
   name varchar(255),
   primary key (id)
);

drop table if exists requests cascade;
create table requests (
   id bigint generated by default as identity,
   description varchar(200),
   created timestamp,
   requestor_id bigint references users(id),
   primary key (id)
);

drop table if exists items cascade;
create table items (
   id bigint generated by default as identity,
   is_available boolean not null,
   description varchar(200),
   name varchar(255),
   owner_id bigint references users(id),
   request_id bigint references requests(id),
   primary key (id)
);

drop table if exists bookings cascade;
create table bookings (
   id bigint generated by default as identity,
   end_date timestamp,
   start_date timestamp,
   status varchar(255),
   booker_id bigint references users(id),
   item_id bigint references items(id),
   primary key (id)
);

drop table if exists comments cascade;
create table comments (
   id bigint generated by default as identity,
   created timestamp,
   text varchar(255),
   author_id bigint references users(id),
   item_id bigint references items(id),
   primary key (id)
);

